name: SonarQube Code Quality Check
on:
  push:
  pull_request:

jobs:
  call-code-quality-workflow:
    uses: n-ablePrivateLimitedColomboSriLanka/Reusable-workflow-for-Java/.github/workflows/reusable.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ github.event.repository.name }}
